/**
 * Public entry point for `@surrealdb/mql`. Everything exported from here
 * forms the contract that downstream code may rely on; internals live in
 * `client/`, `db/`, `collection/`, `cursor/`, `surreal/`, and `translators/`.
 */

export { MongoClient } from "./client/mongo-client.ts";
export { Collection } from "./collection/collection.ts";
export { FindCursor } from "./cursor/find-cursor.ts";
export {
	ListIndexesCursor,
	type ListIndexesRunner,
} from "./cursor/list-indexes-cursor.ts";
export { Db } from "./db/db.ts";
export type {
	MongoErrorCodeValue,
	MongoServerErrorOptions,
	WriteError,
} from "./errors.ts";
export {
	codeNameFor,
	MongoAPIError,
	MongoClientError,
	MongoCompatibilityError,
	MongoCursorExhaustedError,
	MongoCursorInUseError,
	MongoDriverError,
	MongoError,
	MongoErrorCode,
	MongoErrorLabel,
	MongoExpiredSessionError,
	MongoInvalidArgumentError,
	MongoNetworkError,
	MongoNetworkTimeoutError,
	MongoNotConnectedError,
	MongoOperationTimeoutError,
	MongoParseError,
	MongoRuntimeError,
	MongoServerError,
	MongoServerSelectionError,
	MongoSystemError,
	MongoTopologyClosedError,
	MongoTransactionError,
	MongoWriteConcernError,
} from "./errors.ts";
export { ObjectId } from "./object-id.ts";
export type {
	ClientSessionId,
	ClientSessionOptions,
	EndSessionOptions,
	TransactionOptions,
	WithSessionCallback,
	WithTransactionCallback,
} from "./session/client-session.ts";
export { ClientSession } from "./session/client-session.ts";
export { Transaction, TransactionState } from "./session/transaction.ts";
export type {
	AbstractCursorOptions,
	Auth,
	AuthMechanism,
	BSONSerializeOptions,
	BulkWriteOptions,
	BulkWriteResult,
	CollationOptions,
	CollectionInfo,
	CommandOperationOptions,
	CompressorName,
	CountDocumentsOptions,
	CreateIndexesOptions,
	CreateIndexOptions,
	DeleteOptions,
	DeleteResult,
	DistinctOptions,
	Document,
	DriverInfo,
	DropIndexesOptions,
	EstimatedDocumentCountOptions,
	ExplainOptions,
	Filter,
	FindOneAndDeleteOptions,
	FindOneAndReplaceOptions,
	FindOneAndUpdateOptions,
	FindOptions,
	Hint,
	IndexDescription,
	IndexDescriptionCompact,
	IndexDescriptionInfo,
	IndexDirection,
	IndexInformationOptions,
	IndexKey,
	IndexSpecification,
	IndexSpecificationOptions,
	InsertManyResult,
	InsertOneOptions,
	InsertOneResult,
	ListIndexesOptions,
	ModifyResult,
	MongoClientOptions,
	OperationOptions,
	OptionalId,
	PkFactory,
	Projection,
	ReadConcernLevel,
	ReadConcernLike,
	ReadPreferenceLike,
	ReadPreferenceMode,
	ReconnectSettings,
	ReplaceOptions,
	ServerApi,
	ServerApiVersion,
	ServerMonitoringMode,
	Sort,
	SortDirection,
	TagSet,
	UpdateFilter,
	UpdateOptions,
	UpdateResult,
	W,
	WithoutId,
	WriteConcernOptions,
	WriteConcernSettings,
} from "./types.ts";
